### ISSUE TITLE
Deprecation issues with phpunit 8

### ISSUE THREAD

**Issue by rbaarsma** [mockery/mockery#1024]
```
  1x: The "Mockery\Adapter\Phpunit\Legacy\TestListenerForV7" class implements "PHPUnit\Framework\TestListener" that is deprecated Use the `TestHook` interfaces instead.

  1x: The "Mockery\Adapter\Phpunit\Legacy\TestListenerForV7" class uses "PHPUnit\Framework\TestListenerDefaultImplementation" that is deprecated The `TestListener` interface is deprecated.
```
I'm guessing we need a `Mockery\Adapter\Phpunit\Legacy\TestListenerForV8` class to migrate this in a similar way as the existing V7, V6 and V5

**Comment by rbaarsma** [comment]
Solution is something like this

```
class PHPUnitExtension implements BeforeTestHook, AfterTestHook
{
    public function __construct()
    {
        $this->trait = new TestListenerTrait();
    }

    public function executeBeforeTest(string $test): void
    {
        $this->trait->startTestSuite();
    }

    public function executeAfterTest(string $test, float $time): void
    {
        $this->trait->endTest($test, $time);
    }
}
```

Used as an extension in `phpunit.xml.dist`:
```
    <extensions>
        <extension class="Mockery\Adapter\Phpunit\TestExtension" />
    </extensions>
```

For this last, we need to update the docs.

Note: extensions are usable from phpunit >= 7.1

**Comment by GrahamCampbell** [comment]
This has been fixed in the 1.4 series @davedevelopment?

**Comment by davedevelopment** [comment]
I thought so, I think we nailed everything...

**Comment by GrahamCampbell** [comment]
> Note: extensions are usable from phpunit >= 7.1

@rbaarsma I think the situation is Mockery doesn't support PHPUnit 8 together with PHP 7.1 or 7.2. If you are using PHP 7.2 or lower with Mockery, PHPUnit 7 is the newest version of PHPUnit you can use. If you want to use PHPUnit 8 or newer, you must have PHP 7.3 or higher. I think this restriction is fine. You'll just need to make sure your builds pull the correction version combinations.

**Comment by trickeyone** [comment]
@GrahamCampbell I've updated my projects to 9.3.8 and the warning messages are still appearing. I see that the composer.json says it conflicts with PHPUnit <8.0, wouldn't it be prudent to use the new PHPUnit interfaces as indicated?

I am also seeing this message:
```
1x: The "Mockery\Adapter\Phpunit\TestListener" class uses "PHPUnit\Framework\TestListenerDefaultImplementation" that is deprecated
```

**Comment by trickeyone** [comment]
After looking into this a bit more, and looking at PHPUnit's own repo, I found sebastianbergmann/phpunit#3390. So, I think this is more on PHPUnit to fix the TestHook implementation before anything can really be done. With the current iteration of the TestHook architecture, I wasn't able to find an easy way to add Mockery's pre- or post-test hook functionality, as the `Test` object nor the `TestResult` are passed to the hook. Which was also brought up by greg0ire (https://github.com/sebastianbergmann/phpunit/issues/3390#issuecomment-546121491) in reference to Symfony's PHPUnit Bridge.
